clear all; close all; clc;
addpath("utils\")

fprintf('Scanning gamma values for final relative Linf error.\n');

%% Domain and numerics
P = get_sim_params();

N  = P.N;
a  = P.a;
M  = P.M;
b  = P.b;
Lx = P.Lx;
T  = P.T;

c  = P.c;
gamma = P.gamma; % ignore
nu = P.nu;

dh = P.dh;
dt = P.dt;
J  = P.J;

%% Single eigenmode parameters
n0    = 1;
A0    = 1.0;
v0amp = 0.0;

k0     = n0*pi/Lx;
omega0 = c*k0;

%% Gamma range
gamma_vals = 0:1:100;
Ng = numel(gamma_vals);

rel_Linf_final = zeros(Ng,1);

%% Spatial grid (fixed for all runs)
% But will be regenerated by run_fdtd anyway.
% We only need x for analytic solution.
% So we get Nx, Nt after first simulation.
first_run_done = false;

for ig = 1:Ng
    gamma = gamma_vals(ig);
    fprintf('gamma = %d\n', gamma);

    %% FDTD simulation
    u_fdtd = run_fdtd(@(x) A0*sin(k0*x), ...
                         @(x) v0amp*sin(k0*x), ...
                         Lx, T, c, dh, dt, gamma, nu);

    Nx = size(u_fdtd,1);
    Nt = size(u_fdtd,2);

    x = linspace(0,Lx,Nx).';
    t = linspace(0,T,Nt);

    %% Analytical solution
    u_an = analytic_solution_single_mode(x, t, c, gamma, nu, k0, A0, v0amp);

    %% Final-time error
    diff  = u_fdtd(:,end) - u_an(:,end);
    abs_Linf_final = max(abs(diff));
    abs_Linf_ref   = max(abs(u_an(:,end)));
    rel_Linf_final(ig) = abs_Linf_final / max(abs_Linf_ref, 1e-15);
end

%% Plot results
figure;
semilogy(gamma_vals, rel_Linf_final, 'LineWidth', 2);
xlabel('\gamma'); ylabel('Final relative L_\infty error');
title('Final relative Linf error vs damping coefficient \gamma');
grid on;
